- name: Show Secrets
  hosts: servers
  become: yes

  vars_files:
    - secrets.yml

  tasks:
    - name: Show pass
      debug:
        msg: "M password is {{ password }}"

    - name: Show username
      debug:
        msg: "My API key is {{ api }}" 

