#SPDX-License-Identifier: MIT-0
---
# tasks file for role/docker
- name: Update system
  apt:
    name: "*"
    state: latest

- name: Install docket
  apt:
    name: docker.io
    state: latest

- name: Add users to Docker
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Register docker version
  command: docker --version
  register: docker_version

- name: Show docker version
  debug:
    msg: "{{ docker_version }}"

- name: Show containers
  command: docker ps
  